### ISSUE TITLE
Table of contents is broken

### ISSUE THREAD

**Issue by MedicalJewel105** [Bedrock-OSS/bedrock-wiki#140]
Table of contents is broken, it doesn't link you to place where it should

https://user-images.githubusercontent.com/87320205/126954348-c11c507a-74ff-449e-abfd-7658770bbfbe.mp4

**Comment by MedicalJewel105** [comment]
Somewhere it work but it should show in the upper part of screen.
Not like this:
![image](https://user-images.githubusercontent.com/87320205/126968472-4446bb24-687c-44dc-b44f-2bcd3a4fa158.png)
But like this:
![image](https://user-images.githubusercontent.com/87320205/126968512-ff213d7e-2319-4f71-8f1e-bb9f6ea96655.png)

**Comment by SirLich** [comment]
Seems to be caused by the jumpto-being offset by the size of the toc. Large tocs make a very large offset, to the point where clicking a top item appears to jump TO the toc. 

Click a bottom item, and it will actually bring you down the page, but you need to scroll the length of the toc to actually find the right item.

**Comment by MedicalJewel105** [comment]
Caused by scaling in browser more than 100%

**Comment by Fabrimat** [comment]
I can't reproduce this on Chrome 105.0.5195.127. Got the scaling to 250% but the toc jumped to the right place.

**Comment by SmokeyStack** [comment]
This issue is no longer present and has been stale for over 3 years now.
